
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - racing-net

  gocar-a:
    image: gocar:latest
    build:
      context: ./gocar
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=A
    volumes:
      - ./learning-data/car-a:/data
    depends_on:
      - server     
    networks:
      - racing-net

  gocar-b:
    image: gocar:latest
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=B
    volumes:
      - ./learning-data/car-b:/data
    depends_on:
      - server     
    networks:
      - racing-net

  gocar-c:
    image: gocar:latest
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=C
    volumes:
      - ./learning-data/car-c:/data
    depends_on:
      - server     
    networks:
      - racing-net

  gocar-d:
    image: gocar:latest
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=D
    volumes:
      - ./learning-data/car-d:/data
    depends_on:
      - server     
    networks:
      - racing-net

  gocar-e:
    image: gocar:latest
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=E
    volumes:
      - ./learning-data/car-e:/data
    depends_on:
      - server     
    networks:
      - racing-net

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8081:8081"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yml
    depends_on:
      - server
    networks:
      - racing-net

  observer:
    build:
      context: ./observer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - envoy  
    networks:
      - racing-net

networks:
  racing-net:
    driver: bridge