version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - racing-net
  gocar-c:
    build:
      context: ./gocar
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=C
    depends_on:
      - server     
    networks:
      - racing-net 

  gocar-a: 
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=A
    build:
      context: ./gocar
      dockerfile: Dockerfile 
    depends_on:
      - server     
    networks:
      - racing-net       
  gocar-b:
    build:
      context: ./gocar
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=B
    depends_on:
      - server     
    networks:
      - racing-net   
  gocar-d:
    build:
      context: ./gocar
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=D
    depends_on:
      - server     
    networks:
      - racing-net   
  gocar-e:
    build:
      context: ./gocar
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDR=server:50051 
      - CAR_LETTER=E
    depends_on:
      - server     
    networks:
      - racing-net         
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8081:8081"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yml
    depends_on:
      - server
    networks:
      - racing-net

  observer:
    build:
      context: ./observer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - envoy
    networks:
      - racing-net
  # human-player:
  #   build:
  #     context: ./humanplayer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9090:80"
  #   depends_on:
  #     - server
  #     - envoy
  #   networks:
  #     - racing-net
  #   deploy:
  #     replicas: 0  
networks:
  racing-net:
    driver: bridge