version: '3.8'

services:
  grpc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - racing-net

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8081:8081"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yml
    depends_on:
      - grpc-server
    networks:
      - racing-net

  web-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - grpc-server
      - envoy
    networks:
      - racing-net

networks:
  racing-net:
    driver: bridge